((nil . ((fill-column . 120)))
 (js2-mode . ((js2-basic-offset . 2)))
 (web-mode . ((web-mode-markup-indent-offset . 2)
              (web-mode-code-indent-offset . 2)
              (web-mode-css-indent-offset . 2))))
